[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[fuzz]
runs = 256 # will be supplied random data from 0 to uint256.max(), as many times as you've conifigured runs
#seed = '0x2'

# [invariant]
# runs = 64
# depth = 32 # Number of functions called in a single command
# fail_on_revert = true # if we want to revert when they revert
# # If is fail whe dont care and throw a panic error